f = open(r'.\sionyx-kiosk-wpf\src\SionyxKiosk\Views\Windows\AuthWindow.xaml', encoding='utf-8')
c = f.read()
f.close()
count = c.count('Style="{StaticResource BtnPrimary}"')
print(f'Found {count} matches')
c = c.replace('Style="{StaticResource BtnPrimary}"', 'Style="{StaticResource BtnPrimaryDynamic}"')
f = open(r'.\sionyx-kiosk-wpf\src\SionyxKiosk\Views\Windows\AuthWindow.xaml', 'w', encoding='utf-8')
f.write(c)
f.close()
print('OK')
