f = open(r'.\src\SionyxKiosk\Views\Windows\AuthWindow.xaml', encoding='utf-8')
c = f.read()
f.close()
print(f'Total Viewbox count: {c.count("<Viewbox")}')
print(f'Total Canvas count: {c.count("<Canvas")}')
