content = open(r'.\src\SionyxKiosk\Views\Windows\MainWindow.xaml', encoding='utf-8').read()
old = 'RadioButton x:Name="NavHelp" AutomationProperties.AutomationId="NavHelp" Tag="Help"\n                                 Style="{StaticResource SidebarNavButton}"\n                                 Checked="NavButton_Checked" GroupName="Nav">\n                        <StackPanel Orientation="Horizontal">\n                            <TextBlock Text="&#xE897;" FontFamily="Segoe MDL2 Assets"\n                                       FontSize="16" VerticalAlignment="Center" Margin="0,0,10,0" />\n                            <TextBlock Text="\u05e2\u05d6\u05e8\u05d4" FontSize="15" VerticalAlignment="Center" />\n                        </StackPanel>\n '
new = 'RadioButton x:Name="NavMessages" AutomationProperties.AutomationId="NavMessages" Tag="Messages"\n                                 Style="{StaticResource SidebarNavButton}"\n                                 Checked="NavButton_Checked" GroupName="Nav">\n                        <StackPanel Orientation="Horizontal">\n                            <TextBlock Text="&#xE715;" FontFamily="Segoe MDL2 Assets"\n                                       FontSize="16" VerticalAlignment="Center" Margin="0,0,10,0" />\n                            <TextBlock Text="\u05d4\u05d5\u05d3\u05e2\u05d5\u05ea" FontSize="15" VerticalAlignment="Center" />\n                        </StackPanel>\n                    </RadioButton>\n                    <RadioButton x:Name="NavHelp" AutomationProperties.AutomationId="NavHelp" Tag="Help"\n                                 Style="{StaticResource SidebarNavButton}"\n                                 Checked="NavButton_Checked" GroupName="Nav">\n                        <StackPanel Orientation="Horizontal">\n                            <TextBlock Text="&#xE897;" FontFamily="Segoe MDL2 Assets"\n                                       FontSize="16" VerticalAlignment="Center" Margin="0,0,10,0" />\n                            <TextBlock Text="\u05e2\u05d6\u05e8\u05d4" FontSize="15" VerticalAlignment="Center" />\n                        </StackPanel>\n '
count = content.count(old)
print(f"Found {count} matches")
if count == 1:
    content = content.replace(old, new, 1)
    open(r'.\src\SionyxKiosk\Views\Windows\MainWindow.xaml', 'w', encoding='utf-8').write(content)
    print('OK')
else:
    print('NOT FOUND')
